server:
  port: 8080

spring:
  application:
    name: site-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_platform
    username: postgres
    password: 123456aaAA
    platform: postgresql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    preferIpAddress: true